# -*- coding: utf-8 -*-
"""spotify_tracks_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrQ32Fi8VE7PLjjRPlkl8XjQvR_ovUjq

# Introduction

Using the dataset stored in Kaggle (https://www.kaggle.com/datasets/yashdev01/spotify-tracks-dataset) I seek to answer if the popularity of a song on Spotify can be explained through its musical characteristics

This project explores a Spotify song dataset containing 125 different genres,
to find relationships between the acoustic characteristics of the tracks and their popularity. The goal is to understand what attributes are associated with the most popular songs and what differentiates them from other songs.

# Load and Data Cleaning
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('spotify-tracks-dataset.csv')
df.drop_duplicates(inplace=True)

df.info()

"""There are three columns where a record is null: _artists_, _album\_name_ and _track\_name_. Let's look at the registry to find out how to handle it."""

# Find the record where artists, album_name and track_name is null
df.loc[
    df[['artists', 'album_name', 'track_name']].isna().any(axis=1),
    'track_id'
]

"""The song with the track_id 1kR4gIb7nGxHPI3D2ifs59 belongs to a song deleted from Spotify, which is why we chose to completely eliminate the record from the analysis."""

# We found a track with null values ​​in artists, album_name, track_name.
## Let's find the clue and eliminate it.
df = df.dropna(subset=["track_name", "artists"])

# We are also going to remove the "Unnamed: 0.1" and "Unnamed: 0" columns
df[["Unnamed: 0", "Unnamed: 0.1"]].head()
df = df.drop(columns=["Unnamed: 0", "Unnamed: 0.1"])

"""A record was detected with null values ​​in key variables (_track_name, artists and album_name_). Checking the _track\_id_ identified that it corresponded to a deleted song. (https://open.spotify.com/track/1kR4gIb7nGxHPI3D2ifs59)

**It was chosen to completely delete the dataset record**
The columns _"Unnamed: 0"_ and _Unnamed: 0.1_ generated by previous exports of the dataset (Unnamed) were also eliminated, since they did not provide relevant information for the analysis.
"""

df.info()

"""# Exploratory Data Analysis

## What are the most popular songs?
"""

# We will show just a few features to make it easier to view the table
df[['track_id', 'artists', 'album_name', 'track_name', 'popularity', 'track_genre']].sort_values(by='popularity', ascending=False).head()

"""The unit of analysis of this dataset is not the song, it is the genre, which is why in the first two positions we find exactly the same song: **Unholy (feat. Kim Petras)**, the only difference between both rows is that one is classified as **pop** genre and the other as **dance**.
This means that genres for Spotify are individual tags.

To really find the top 5 most popular songs on Spotify we need to count only those unique records with a unique _track\_id_:
"""

# A new dataframe is created using the songs "track_id" as the unit of analysis
df_tracks = df.drop_duplicates(subset="track_id")

# And the original dataframe is renamed
df_genre = df

# Top 5 most popular songs
df_tracks[['track_name', 'popularity', 'track_genre']].sort_values(by='popularity', ascending=False).head()

"""The most popular songs are:
1. Unholy (feat. Kim Petras) - "dance" genre
2. Quevedo: Bzrp Music Sessions, Vol. 52 "hip-hop" genre
3. I'm Good (Blue) - "dance" genre
4. Bachata - "Latin" genre
5. Me Porto Bonito - "Latin" genre

## Popularity Distribution
"""

plt.hist(df_tracks["popularity"], bins=60, color='#1DB954')
plt.title("Popularity Distribution by Song")
plt.xlabel('Popularity Points')
plt.ylabel("Frequency")

plt.savefig("figures/popularity_distribution_by_song.png", dpi=150)

"""We can observe with the histogram a long-tail distribution, where many songs are very unpopular, while very few songs concentrate popularity, this is expected and is a behavior dictated by virality, algorithms, marketing and culture.

There is a huge peak near 0.
But it is important to remember that this metric does not measure quality but rather popularity and interaction based on recent views.
"""

# Popularity statistics by song
df_tracks["popularity"].describe()

# Popularity statistics by genre
df_genre['popularity'].describe()

"""We can see a **mean of 33.19** and a median of **33.00** when we analyze the songs, the difference is not abysmal but it exists, and confirms the asymmetry observed in the histogram.
- 75% of the songs are below 49% popularity.
This means that **3 out of every 4 songs on Spotify do not reach 50% popularity**
- The standard deviation of 20.58 tells us about a fairly dispersed data set, this means that the songs are typically about 20 points above or below the average, the popularity is quite variable between songs.

Practically the same thing happens when we analyze the songs by unit of their genre (if a song has 4 associated genres, it will appear 4 times).
- Average = 33.23
- Median = 35.00
- Q3 = 50.00

The difference in averages when analyzing the statistics when the unit of measurement is the song and when the unit of measurement is the genre, is minuscule (0.04). This is expected and happens because in the dataset where the unit of measurement is the genre _(df\_genre)_ each song can appear several times,
while in the dataset where the unit of measurement is the song, each song appears only once.

## Distribution of Popularity by Gender
"""

df_genre_grouped_count = df_genre.groupby('track_genre').agg(
  tracks_num=('track_id', 'count')
)

df_genre_grouped_count

"""We have 1000 songs per genre, this dataset was created artificially with the purpose of having the same number of songs per genre to facilitate analysis."""

# Filter by average popularity by genre
avg_popularity = df_genre.groupby('track_genre').agg(
    avg_popularity=('popularity', 'mean')

)

# Top 10 most listened to genres
top10_genres = avg_popularity.sort_values(by='avg_popularity', ascending=False).head(10)

# Average popularity by genre
print(f'Average popularity by genre: {df_tracks['popularity'].mean():.2f}')

# Graphic Representaion
sns.barplot(top10_genres, x='track_genre', y='avg_popularity', color='#1DB954')

plt.axhline(y=33.20, linestyle='--', color='black', label='Overall average (33.20)')

plt.title('Top 10 Most Popular Genres')
plt.xlabel('Genre')
plt.ylabel('Average Popularity')
plt.xticks(rotation=90)

plt.show()
plt.savefig("figures/top10_most_popular_genres.png", dpi=150)

top10_genres.head(10)

"""The 5 most popular genres **do not coincide with the genres of the most popular songs** this is because the most popular songs are hits, but it does not mean that the entire genre they represent has more songs that are equally popular,
while these genres represented in the bar graph are **consistently more popular** than the rest.

The most popular genres are above the average popularity by 13 to 27 points.

If we analyze the genres with the highest average popularity value we find:
1. **pop_film** | 59.28 average popularity points and a standard deviation of 10.24.
2. **k-pop** | 56.95 average popularity points and a standard deviation of 16.85.
3. **chill** | 53.65 average popularity points and a standard deviation of 14.
95.
4. **sad** | 52.37 average popularity points and a standard deviation of 11.49.
5. **grunge** | 49.59 average popularity points and a standard deviation of 18.48.

It is important to remember that too high a standard deviation means that songs of a certain genre are not stable in terms of popularity. That is to say;

- A high average popularity and a low deviation means that **the genre is stable and consistently popular**

- A high average popularity and a high deviation means that **the genre has some hits and others isolated**

-
A low average popularity and a low deviation means that **the songs are consistently unpopular**

- A low average popularity and a high deviation means that **there are few isolated hits**

It is important to note that **none of the 5 most popular songs are within the 5 most popular genres**

It seems that the most popular song genres (dance, hip-hop, and Latin) have very few hits, but these songs sound a lot.

## Distribution of Popularity by Genre
"""

plt.figure(figsize=(10,6))

# Generate a list containing the names of the 10 most popular genres
top_genres_list = top10_genres.index.tolist()

# Filter df_genres to only get records for songs that match the most popular genres
top10_genres_box = df_genre[df_genre['track_genre'].isin(top_genres_list)]

# Graphic Representation
sns.boxplot(
    data=top10_genres_box,
    x='track_genre',
    y='popularity',
    color='#1DB954'
)

plt.title('Distribution of Popularity by Genre')
plt.xlabel('Genre')
plt.ylabel('Popularity')

plt.xticks(rotation=90) # Rotate x-axis labels for better readability
plt.show()
plt.savefig("figures/distribution_of_popularity_by_genre", dpi=150)

top10_genres_box

"""- The pop genre shows the greatest variability in popularity, (Q3 and Q1 are very far apart), with songs ranging from very low values ​​to some of the highest in the dataset.

- The most stable genre is sertanejo, few outliers and many songs with the same popularity

## Maximum Popularity Score by Genre
"""

# Calculate max. popularity score
df_genre_max = df.groupby('track_genre')['popularity'].max().sort_values(ascending=False)
df_genre_max

"""The most popular song in the _dance_ genre has 100 popularity points, but this does not mean that all or most songs have the same popularity points, this simply confirms how outliers can drastically move the position of a feature in a leaderboard.

## Correlation between characteristics
"""

corr = df_tracks.corr(numeric_only=True)

plt.figure(figsize=(15,8))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation between characteristics')
plt.show()
plt.savefig("figures/correlation_heatmap", dpi=150)

"""- **energy-loudness**: Intensity, which tells us about how intense a song is perceived on a scale from 0 to 1, is highly correlated with volume. These two characteristics have a **correlation of 0.76**. This means that when a song has more energy, it also tends to be louder. This makes a lot of sense,
energetic songs (rock, EDM, modern pop) are usually mixed louder on purpose.

- **valence-danceability**: Valence (emotional tone of a song) and danceability (how easy it is to dance to a song) are two other variables that usually move together. **With a correlation of 0.49**, although not very high, it reveals something to us. **The most danceable songs tend to have a more positive emotional tone**

- **explicit-speechiness**: The _explicit_ characteristic is boolean and explains whether a song has explicit language (1) or not (0), in turn, _speechiness_ measures how much spoken content there is in a song. It stands to reason that if a song has explicit language, it will always have to have lyrics, so for this characteristic to be true,
_speechiness_ will have to be a high value, or at least not 0.

## Is there a characteristic strongly correlated with popularity?

There is no characteristic in this dataset that demonstrates a very high correlation, not even a medium correlation, all the values ​​obtained indicate very low correlations, in a range of -0.13 to 0.072. The largest is between **popularity - loudness = 0.72** (popularity and volume).
It seems that **the success of a song is not explained only through its acoustic characteristics** and despite the existing correlation between musical characteristics.

Culture, social context, media exposure and marketing weigh as much or more than musical characteristics.
"""

# Graphical demonstration of some correlations
sns.scatterplot(data=df_tracks, x='popularity', y='loudness', color='#1DB954')
plt.title('Populrity vs. Loudness')

plt.show()
plt.savefig("figures/popularity_vs_loudness.png", dpi=150)

sns.scatterplot(data=df_tracks, x='popularity', y='danceability', color='#1DB954')
plt.title('Popularity vs. Danceability')

plt.show()
plt.savefig("figures/popularity_vs_danceability.png", dpi=150)

"""On the left side of the scatter graph we can see the least popular songs, their volume is quite varied and they are found throughout the entire volume range in decibels, this means that there are unpopular songs with high and low volume.
If we continue moving to the right we will see that the area occupied by the songs along the y axis decreases. This tells us several things:
1. There are very few popular songs.
2. Popular songs are rarely very quiet, on the contrary, they are quite loud (For Spotify 0 db is the maximum figure).

# Conclusions

Music does not follow a clear pattern in terms of popularity, it is evident that the most popular songs within this dataset are:
- Unholy (feat. Kim Petras) - "dance" genre
- Quevedo: Bzrp Music Sessions, Vol. 52 "hip-hop" genre
- I'm Good (Blue) - "dance" genre
- Bachata - "latin" genre
- Me Porto Bonito - "Latin" genre

Different genres, with a danceability above 0.56, a different mode, in some major, and in some minor, and a quite varied valence. It is to be expected that the characteristics of these songs are not exactly the same for each of them, but there is no clear pattern either. In fact,
None of the 5 most popular songs are within the 5 most popular genres, these are:  
- pop_film
- k-pop
- chill
- sad
- grunge

This means that the most popular genres have many songs that are listened to a lot but none become extremely popular, on the contrary, the most popular songs are extraordinary cases of genres that do not usually stand out,
but they have one or two hits so big that they end up becoming the most popular song genres.

When studying the correlation between the characteristics, there was no evidence that any of these musical characteristics influenced the popularity of a song.

Even though characteristics (not including popularity) relate to and affect each other, popularity never seems affected by tempo, valence, danceability, or even mood of the song, these musical characteristics take a backseat in today's music industry. Marketing seems to have much more weight,
the virality, the controversy and the weight generated by conversations through social networks than the musical structure of the song itself.

It is clear that it seems an almost impossible task to predict through this data whether a song may or may not be popular; it is a natural human behavior to be influenced not only by musical richness when choosing a song but also by the environment in which we find ourselves.
"""